export const CREATE_USER = 'CREATE_USER';
export const LOG_IN_USER = 'LOGIN_IN_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const SEARCH_USER = 'SEARCH_USER';


export const UPLOAD_IMAGE_CAMERA = 'UPLOAD_IMAGE_CAMERA';
export const UPLOAD_FILE_CLOUD = 'UPLOAD_FILE_CLOUD';
export const SAVE_UPLOAD_SERVER = 'SAVE_UPLOAD_SERVER';

export const FETCH_USER_FILES = 'FETCH_USER_FILES';
export const FETCH_RECENT_FILES = 'FETCH_RECENT_FILES';
export const FETCH_SINGLE_FILE_VIEW = 'FETCH_SINGLE_FILE_VIEW';



