export const CREATE_USER = 'CREATE_USER';
export const LOG_IN_USER = 'LOGIN_IN_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const SEARCH_USER = 'SEARCH_USER';
export const FIND_ONE_SEARCH = 'FIND_ONE_SEARCH';
export const USER_FOLLOW = 'USER_FOLLOW';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const EDIT_USER = 'EDIT_USER';


export const UPLOAD_IMAGE_CAMERA = 'UPLOAD_IMAGE_CAMERA';
export const UPLOAD_FILE_CLOUD = 'UPLOAD_FILE_CLOUD';
export const SAVE_UPLOAD_SERVER = 'SAVE_UPLOAD_SERVER';
export const ADD_UPLOAD_CATEGORY = 'ADD_UPLOAD_CATEGORY';

export const FETCH_USER_FILES = 'FETCH_USER_FILES';
export const FETCH_RECENT_FILES = 'FETCH_RECENT_FILES';
export const FETCH_SINGLE_FILE_VIEW = 'FETCH_SINGLE_FILE_VIEW';
export const LIKE_USER_FILE = 'LIKE_USER_FILE';
export const UNLIKE_USER_FILE = 'UNLIKE_USER_FILE';
export const PREVIOUSLY_LIKED_FILE = 'PREVIOUSLY_LIKED_FILE';
export const USER_LIKED_FILES = 'USER_LIKED_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const RESET_LIKED_FILE = 'RESET_LIKED_FILE';

export const SEND_MESSAGE_USER = 'SEND_MESSAGE_USER';
export const PREVIOUS_MESSAGES = 'PREVIOUS_MESSAGES';
export const PENDING_MESSAGES = 'PENDING_MESSAGES';
export const CURRENT_MESSAGE = 'CURRENT_MESSAGE';
export const USER_CONVERSATION_MESSAGE = 'USER_PREVIOUS_MESSAGE';
export const NEW_USER_MESSAGE = 'NEW_USER_MESSAGE';
export const MESSAGE_SCREEN_SHOWING = 'MESSAGE_SCREEN_SHOWING';
export const CURRENT_MESSAE_USER = 'CURRENT_MESSAE_USER';
export const GET_CONVERSATION_LIST = 'GET_CONVERSATION_LIST';
export const SEND_CONVERSATION_REPLY = 'SEND_CONVERSATION_REPLY';


export const GET_EVENTS = 'GET_EVENTS';
export const GET_SPONSORED = 'GET_SPONSORED';





